FROM patrickhulce/lhci-server:latest

# 设置工作目录
WORKDIR /usr/src/lhci

# 暴露端口
EXPOSE 9001

# 设置环境变量
ENV PORT=9001
ENV LHCI_STORAGE__SQL_DATABASE_PATH=/data/db.sql
ENV LHCI_STORAGE__SQL_DIALECT=sqlite

# 创建数据目录
RUN mkdir -p /data

# 设置卷挂载点
VOLUME ["/data"]

# 启动命令
CMD ["lhci", "server"]
