app = "ten-shoes-lhci"
primary_region = "sjc"

[build]
  image = "patrickhulce/lhci-server:latest"

[env]
  PORT = "9001"
  LHCI_STORAGE__SQL_DATABASE_PATH = "/data/db.sql"

[http_service]
  internal_port = 9001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "lhci_data"
  destination = "/data"

[machine]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
